### ISSUE TITLE
Requirements.txt missing

### ISSUE THREAD

**Issue by mvcisback** [koulanurag/mmn#1]
@koulanurag You mention a requirements.txt in the repository. I have been attempting to reproduce this work, but it seems some of the dependency chain may have rotted.

Would you mind uploading the requirements.txt?

Thank you!

**Comment by koulanurag** [comment]
Hi @mvcisback 
Thanks for bringing it our notice.
We have added the ```requirements.txt``` file. 

Let us know, if you face any more issue.
Best,
Anurag

**Comment by mvcisback** [comment]
Thanks. The recent change seems to have fixed things!
