### ISSUE TITLE
Tomita Grammer's Code missing

### ISSUE THREAD

**Issue by mvcisback** [koulanurag/mmn#2]
`main_tomita.py` seems to implement the `gym_x` api.

**Comment by koulanurag** [comment]
Hi @mvcisback 
The ```requirements.txt```  file would help you to resolve it.

Also, you can also access the ```gym_x``` package from [here](https://github.com/koulanurag/gym_x).

Again, Thanks for bringing it to our notice.

Best,
Anurag

**Comment by mvcisback** [comment]
I see. This seems to have been fixed by having the requirements.txt. Thanks!
